### ISSUE TITLE
detection API for 4 channels objects

### ISSUE THREAD

**Issue by laupl0082** [minhnhat93/tf_object_detection_multi_channels#2]
Hi, 
first of all, thanks for your work and for sharing it.
I am trying to modify the detection API for 4 channels objects, RGB+Depth.
I followed and modified the files as you suggested, but when I try to start training, I get the following error:

Traceback (most recent call last):
  File "/home/xxx/.local/lib/python3.5/site-packages/tensorflow/python/framework/common_shapes.py", line 654, in _call_cpp_shape_fn_impl
    input_tensors_as_shapes, status)
  File "/home/xxx/anaconda3/lib/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/home/xxx/.local/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimensions must be equal, but are 3 and 4 for 'Preprocessor/sub' (op: 'Sub') with input shapes: [1,?,?,3], [1,1,4].

I am working on trying to resolve it and I was wondering if you encountered anything similar and you alredy know what must be modified.
In addition, I would like to know which tensorflow version you used (my guess is not the latest) because, for example, the modification 
optional uint32 num_input_channels = 28 [default=3];
in object_detection/protos/faster_rcnn.proto has to be modify to   
optional uint32 num_input_channels = 30 [default=3]; 
since the following 
optional HardExampleMiner hard_example_miner = 28;
is present. 
So, I would like to understand if my error is due to TF version (new TF requires additional changes) or something else.

BTW, thanks again!

**Comment by laupl0082** [comment]
actually [1,1,4] refers to the channel_means in faster_rcnn_resnet_v1_feature_extractor.py, so I think the input tensor is not properly recognized as it should be

**Comment by ghost** [comment]
@laupl0082  I have the same issue, 
object_detection/protos/faster_rcnn.proto:136:40: Field number 28 has already been used in "object_detection.protos.FasterRcnn" by field "hard_example_miner".

Is this a version specific bug?

How did you tackle the preprocessing error?

**Comment by Shiro-LK** [comment]
change the value to a number which is not in the file. 31 works for me.

**Comment by cmbowyer13** [comment]
Make sure you are using the older commit version of TOD

**Comment by Falmi** [comment]
@laupl0082 Did you solved your issue? If you solved it pls tell us the tricks you used. Thanks
