### ISSUE TITLE
Running with num_channels set to 1

### ISSUE THREAD

**Issue by cmbowyer13** [minhnhat93/tf_object_detection_multi_channels#6]
When executing the train.py file i run into this error. I thought i had solved this before, but it's coming back. Not sure if it has to do with how we are encoding the tf records, but this is what mine looks like before i show the error message. def create_tf_example(group,path,files):
    
    with tf.gfile.GFile(os.path.join(path, '{}'.format(str(group.filename)+'.jpg')), 'rb') as fid:
        encoded_jpg = fid.read()
    encoded_jpg = fid.read()
    encoded_jpg_io = io.BytesIO(encoded_jpg)
    image = Image.open(encoded_jpg_io)
    w_jpeg, h_jpeg = image.size
    #print(w_jpeg, h_jpeg)
    
    #define raw data height and width
    h_raw = 512
    w_raw = 7000
    
    filename = (str(group.filename)).encode('utf8')
    image_format = b'.jpg'
    xmins = []
    xmaxs = []
    ymins = []
    ymaxs = []
    classes_text = []
    classes = []
    
    #Conversion factor from jpeg coordinates to raw data coordinates
    jpeg_to_raw_w = w_raw / w_jpeg
    jpeg_to_raw_h = h_raw / h_jpeg
    
    for index, row in group.object.iterrows():
        xmins.append((row['xmin'] * jpeg_to_raw_w) / w_raw)
        xmaxs.append((row['xmax'] * jpeg_to_raw_w) / w_raw)
        ymins.append((row['ymin'] * jpeg_to_raw_h) / h_raw)
        ymaxs.append((row['ymax'] * jpeg_to_raw_h) / h_raw)
        classes_text.append(str(row['class']).encode('utf8')) 
        classes.append(class_text_to_int(str(row['class'])))

    # Read in data as multi-dimensional arrays
    #print(group.filename)
    #print(group.filename2)
    idx = files.index('/media/ssd/JupyterHubNotebooks/calebbowyer/models/object_detection/Object-Detection/images/test4/' + group.filename + '.npy')
    plot_data = np.load(files[idx])
    plot_data = plot_data.reshape(512,7000,1)

    # Encode your matrix input as string
    encoded_inputs = plot_data.tostring()

#     print(encoded_inputs)
#     print("encoded_inputs is: ", encoded_inputs)
        
    tf_example = tf.train.Example(features=tf.train.Features(feature={
        'image/height': dataset_util.int64_feature(h_raw),
        'image/width': dataset_util.int64_feature(w_raw),
        'image/filename': dataset_util.bytes_feature(filename),
        'image/source_id': dataset_util.bytes_feature(filename),
        'image/encoded': dataset_util.bytes_feature(encoded_inputs), #Stores the raw data!
        'image/format': dataset_util.bytes_feature(image_format),
        'image/object/bbox/xmin': dataset_util.float_list_feature(xmins),
        'image/object/bbox/xmax': dataset_util.float_list_feature(xmaxs),
        'image/object/bbox/ymin': dataset_util.float_list_feature(ymins),
        'image/object/bbox/ymax': dataset_util.float_list_feature(ymaxs),
        'image/object/class/text': dataset_util.bytes_list_feature(classes_text),
        'image/object/class/label': dataset_util.int64_list_feature(classes),
        'image/channels': dataset_util.int64_feature(1)
    }))   
    return tf_example

Now this the recurring error message no matter how i change the above TF example. 
 

nstructions for updating:
Please switch to tf.train.get_or_create_global_step
INFO:tensorflow:Summary name /clone_loss is illegal; using clone_loss instead.
/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gradients_impl.py:97: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  **"Converting sparse IndexedSlices to a dense Tensor of unknown shape. "** This line bothers me. 
WARNING:tensorflow:From /usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/clip_ops.py:110: calling reduce_sum (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
WARNING:tensorflow:From /usr/local/lib/python3.5/dist-packages/tensorflow/contrib/slim/python/slim/learning.py:736: Supervisor.__init__ (from tensorflow.python.training.supervisor) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.MonitoredTrainingSession
2018-06-07 13:05:51.876589: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2
INFO:tensorflow:Restoring parameters from faster_rcnn_resnet101_kitti_2018_01_28/model.ckpt
INFO:tensorflow:Starting Session.
INFO:tensorflow:Saving checkpoint to path Training9_FRCNN/model.ckpt
INFO:tensorflow:Starting Queues.
2018-06-07 13:06:22.581377: W tensorflow/core/framework/op_kernel.cc:1198] Invalid argument: assertion failed: [Unable to decode bytes as JPEG, PNG, GIF, or BMP]
         [[Node: case/cond/decode_image/cond_jpeg/cond_png/cond_gif/Assert_1/Assert = Assert[T=[DT_STRING],summarize=3](case/cond/decode_image/cond_jpeg/cond_png/cond_gif/is_bmp, case/cond/decode_image/cond_jpeg/cond_png/cond_gif/Assert_1/Assert/data_0)]]
INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.InvalidArgumentError'>, assertion failed: [Unable to decode bytes as JPEG, PNG, GIF, or BMP]
         [[Node: case/cond/decode_image/cond_jpeg/cond_png/cond_gif/Assert_1/Assert = Assert[T=[DT_STRING],summarize=3](case/cond/decode_image/cond_jpeg/cond_png/cond_gif/is_bmp, case/cond/decode_image/cond_jpeg/cond_png/cond_gif/Assert_1/Assert/data_0)]]
         [[Node: IteratorGetNext = IteratorGetNext[output_shapes=[[], [?], [?,4], [?], [?], [?], [?], [?], [?,?,3], [], [], []], output_types=[DT_STRING, DT_FLOAT, DT_FLOAT, DT_INT64, DT_INT64, DT_INT64, DT_BOOL, DT_FLOAT, DT_UINT8, DT_STRING, DT_INT32, DT_STRING], _device="/job:localhost/replica:0/task:0/device:CPU:0"](Iterator)]]
2018-06-07 13:06:24.613328: W tensorflow/core/framework/op_kernel.cc:1198] Invalid argument: assertion failed: [Unable to decode bytes as JPEG, PNG, GIF, or BMP]
         [[Node: case/cond/decode_image/cond_jpeg/cond_png/cond_gif/Assert_1/Assert = Assert[T=[DT_STRING],summarize=3](case/cond/decode_image/cond_jpeg/cond_png/cond_gif/is_bmp, case/cond/decode_image/cond_jpeg/cond_png/cond_gif/Assert_1/Assert/data_0)]]
2018-06-07 13:06:24.613480: W tensorflow/core/framework/op_kernel.cc:1198] Invalid argument: assertion failed: [Unable to decode bytes as JPEG, PNG, GIF, or BMP]
         [[Node: case/cond/decode_image/cond_jpeg/cond_png/cond_gif/Assert_1/Assert = Assert[T=[DT_STRING],summarize=3](case/cond/decode_image/cond_jpeg/cond_png/cond_gif/is_bmp, case/cond/decode_image/cond_jpeg/cond_png/cond_gif/Assert_1/Assert/data_0)]]
2018-06-07 13:06:24.613542: W tensorflow/core/framework/op_kernel.cc:1198] Invalid argument: assertion failed: [Unable to decode bytes as JPEG, PNG, GIF, or BMP]
         [[Node: case/cond/decode_image/cond_jpeg/cond_png/cond_gif/Assert_1/Assert = Assert[T=[DT_STRING],summarize=3](case/cond/decode_image/cond_jpeg/cond_png/cond_gif/is_bmp, case/cond/decode_image/cond_jpeg/cond_png/cond_gif/Assert_1/Assert/data_0)]]
2018-06-07 13:06:24.614043: W tensorflow/core/framework/op_kernel.cc:1198] Invalid argument: assertion failed: [Unable to decode bytes as JPEG, PNG, GIF, or BMP]
         [[Node: case/cond/decode_image/cond_jpeg/cond_png/cond_gif/Assert_1/Assert = Assert[T=[DT_STRING],summarize=3](case/cond/decode_image/cond_jpeg/cond_png/cond_gif/is_bmp, case/cond/decode_image/cond_jpeg/cond_png/cond_gif/Assert_1/Assert/data_0)]]
2018-06-07 13:06:24.614851: W tensorflow/core/framework/op_kernel.cc:1198] Invalid argument: assertion failed: [Unable to decode bytes as JPEG, PNG, GIF, or BMP]
         [[Node: case/cond/decode_image/cond_jpeg/cond_png/cond_gif/Assert_1/Assert = Assert[T=[DT_STRING],summarize=3](case/cond/decode_image/cond_jpeg/cond_png/cond_gif/is_bmp, case/cond/decode_image/cond_jpeg/cond_png/cond_gif/Assert_1/Assert/data_0)]]
2018-06-07 13:06:29.286529: W tensorflow/core/framework/op_kernel.cc:1198] Invalid argument: assertion failed: [Unable to decode bytes as JPEG, PNG, GIF, or BMP]
         [[Node: case/cond/decode_image/cond_jpeg/cond_png/cond_gif/Assert_1/Assert = Assert[T=[DT_STRING],summarize=3](case/cond/decode_image/cond_jpeg/cond_png/cond_gif/is_bmp, case/cond/decode_image/cond_jpeg/cond_png/cond_gif/Assert_1/Assert/data_0)]]
INFO:tensorflow:global_step/sec: 0
2018-06-07 13:06:29.959738: W tensorflow/core/framework/op_kernel.cc:1198] Invalid argument: assertion failed: [Unable to decode bytes as JPEG, PNG, GIF, or BMP]
         [[Node: case/cond/decode_image/cond_jpeg/cond_png/cond_gif/Assert_1/Assert = Assert[T=[DT_STRING],summarize=3](case/cond/decode_image/cond_jpeg/cond_png/cond_gif/is_bmp, case/cond/decode_image/cond_jpeg/cond_png/cond_gif/Assert_1/Assert/data_0)]]
INFO:tensorflow:Caught OutOfRangeError. Stopping Training.
INFO:tensorflow:Finished training! Saving model to disk.
Traceback (most recent call last):
  File "train.py", line 171, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 124, in run
    _sys.exit(main(argv))
  File "train.py", line 167, in main
    worker_job_name, is_chief, FLAGS.train_dir)
  File "/media/ssd/darpa_data/models/research/object_detection/trainer.py", line 360, in train
    saver=saver)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/slim/python/slim/learning.py", line 782, in train
    ignore_live_threads=ignore_live_threads)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/supervisor.py", line 826, in stop
    ignore_live_threads=ignore_live_threads)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/coordinator.py", line 387, in join
    six.reraise(*self._exc_info_to_raise)
  File "/usr/local/lib/python3.5/dist-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/queue_runner_impl.py", line 250, in _run
    enqueue_callable()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1251, in _single_operation_run
    self._session, None, {}, [], target_list, status, None)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: assertion failed: [Unable to decode bytes as JPEG, PNG, GIF, or BMP]
         [[Node: case/cond/decode_image/cond_jpeg/cond_png/cond_gif/Assert_1/Assert = Assert[T=[DT_STRING],summarize=3](case/cond/decode_image/cond_jpeg/cond_png/cond_gif/is_bmp, case/cond/decode_image/cond_jpeg/cond_png/cond_gif/Assert_1/Assert/data_0)]]
         [[Node: IteratorGetNext = IteratorGetNext[output_shapes=[[], [?], [?,4], [?], [?], [?], [?], [?], [?,?,3], [], [], []], output_types=[DT_STRING, DT_FLOAT, DT_FLOAT, DT_INT64, DT_INT64, DT_INT64, DT_BOOL, DT_FLOAT, DT_UINT8, DT_STRING, DT_INT32, DT_STRING], _device="/job:localhost/replica:0/task:0/device:CPU:0"](Iterator)]]

**Comment by cmbowyer13** [comment]
I also ran into the issue of the frcnn.config complaining about me specifying the num_input_channels parameter.  text_format.Merge(proto_str, pipeline_config)  File "/usr/local/lib/python3.5/dist-packages/google/protobuf/text_format.py", line 533, in Merge
    descriptor_pool=descriptor_pool)
  File "/usr/local/lib/python3.5/dist-packages/google/protobuf/text_format.py", line 587, in MergeLines
    return parser.MergeLines(lines, message)
  File "/usr/local/lib/python3.5/dist-packages/google/protobuf/text_format.py", line 620, in MergeLines
    self._ParseOrMerge(lines, message)
  File "/usr/local/lib/python3.5/dist-packages/google/protobuf/text_format.py", line 635, in _ParseOrMerge
    self._MergeField(tokenizer, message)
  File "/usr/local/lib/python3.5/dist-packages/google/protobuf/text_format.py", line 735, in _MergeField
    merger(tokenizer, message, field)
  File "/usr/local/lib/python3.5/dist-packages/google/protobuf/text_format.py", line 823, in _MergeMessageField
    self._MergeField(tokenizer, sub_message)
  File "/usr/local/lib/python3.5/dist-packages/google/protobuf/text_format.py", line 735, in _MergeField
    merger(tokenizer, message, field)
  File "/usr/local/lib/python3.5/dist-packages/google/protobuf/text_format.py", line 823, in _MergeMessageField
    self._MergeField(tokenizer, sub_message)
  File "/usr/local/lib/python3.5/dist-packages/google/protobuf/text_format.py", line 703, in _MergeField
    (message_descriptor.full_name, name))
**google.protobuf.text_format.ParseError: 12:5 : Message type "object_detection.protos.FasterRcnn" has no field named "num_input_channels".**

Has anyone solved either of these issues?
